apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-healing
  template:
    metadata:
      labels:
        app: self-healing
    spec:
      containers:
        - name: self-healing
          image: jbgaela05/sample-react-app:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: self-healing
spec:
  type: NodePort
  selector:
    app: self-healing
  ports:
    - port: 80
      targetPort: 80
